#!/bin/bash
#
#SBATCH --partition=all
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=16
#SBATCH --mem=20G
#SBATCH --time=04:00:00
#SBATCH -D /home/jmulder6/projects/elastix
#SBATCH -o /home/jmulder6/projects/elastix/shark/make_release-%j.out

module purge > /dev/null 2>&1
module load system/gcc/11.2.0
module load tools/cmake/3.19.2
module load library/boost/1.72.0/gcc-8.3.1
module load library/blas/0.3.13/gcc-8.3.1
module load library/lapack/3.9.0/gcc-8.3.1

git reset --hard && git pull origin develop

ELASTIX_DIR=$PWD
CMAKE_BUILD_TYPE=Release

export CMAKE_BUILD_PARALLEL_LEVEL=16

cmake --no-warn-unused-cli -DCMAKE_BUILD_TYPE:STRING=$CMAKE_BUILD_TYPE -H$PWD -B$PWD/build/$CMAKE_BUILD_TYPE
cmake --build $PWD/build/$CMAKE_BUILD_TYPE --config $CMAKE_BUILD_TYPE --target all

rm -rf $PWD/build/external/src/itk
rm -rf $PWD/build/external/src/plastimatch*
rm -rf $PWD/build/external/src/eigen*