#!/bin/bash
#
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=16
#SBATCH --mem=8G
#SBATCH --time=10-00:00:00
#SBATCH -D /home/jmulder6/projects/elastix/experiments
#SBATCH --mail-type=ALL
#SBATCH --mail-type=END

module purge > /dev/null 2>&1
module load system/gcc/11.2.0
module add system/python/3.8.1

.venv/bin/python experiments/pareto_front.py 1