#!/bin/bash
#
#SBATCH --nodes=1
#SBATCH --ntasks-per-node=16
#SBATCH --mem=8G
#SBATCH --time=10-00:00:00
#SBATCH -D /home/jmulder6/projects/elastix/experiments
#SBATCH -o "output/slurm/pareto_front-%j.out"


module purge > /dev/null 2>&1
module load system/gcc/11.2.0
module add system/python/3.8.1

.venv/bin/python experiments/pareto_front.py 1 $INSTANCE_NR