#!/bin/bash
#
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=16
#SBATCH --mem=8G
#SBATCH --time=20-00:00:00
#SBATCH -D /home/jmulder6/projects/elastix/experiments
#SBATCH -o "output/slurm/run-%j.out"

module purge > /dev/null 2>&1
module --ignore_cache load "system/gcc/11.2.0"

export OMP_NUM_THREADS=16
export OMP_THREAD_LIMIT=16

.venv/bin/python thesispy/experiments/run_json.py
